//set reducer
export const NEW_SPACE = "NEW_SPACE";
export const UPDATE_SET_ID = "UPDATE_SET_ID";
export const TOGGLE_DELETING_SPACE = "TOGGLE_DELETING_SPACE";
export const DELETE_SPACE = "DELETE_SPACE";
export const UPDATE_SET_POSITION = "UPDATE_SET_POSITION";

//main reducer
export const SPACE_CHANGE = "SPACE_CHANGE";
export const INIT_SPACES = "INIT_SPACES";
export const INIT_NOTES = "INIT_NOTES";
export const DONE_LOADING = "DONE_LOADING";
export const TOGGLE_NEW_NOTE_LOADING = "TOGGLE_NEW_NOTE_LOADING";
export const TOGGLE_NEW_SPACE_LOADING = "TOGGLE_NEW_SPACE_LOADING";

//note reducer
export const UPDATE_NOTE_POSITION = "UPDATE_NOTE_POSITION";
export const UPDATE_NOTE_CONTENT = "UPDATE_NOTE_CONTENT";
export const UPDATE_NOTE_TITLE = "UPDATE_NOTE_TITLE";
export const NEW_NOTE = "NEW_NOTE";
export const UPDATE_NOTE_ID = "UPDATE_NOTE_ID";