export const NEW_SPACE = "NEW_SPACE";
export const SPACE_CHANGE = "SPACE_CHANGE";
export const UPDATE_NOTE_POSITION = "UPDATE_NOTE_POSITION";
export const UPDATE_NOTE_CONTENT = "UPDATE_NOTE_CONTENT";
export const UPDATE_NOTE_TITLE = "UPDATE_NOTE_TITLE";